In [13]:
import numpy as np
#min
var=np.array([1,2,3,4,5,3,2])
print(np.min(var))
print(np.sqrt(var))

1
[1.         1.41421356 1.73205081 2.         2.23606798 1.73205081
 1.41421356]


In [3]:
#max
import numpy as np
var=np.array([1,2,3,4,5,3,2])
print(np.max(var))

5


In [5]:
import numpy as np
var=np.array([1,2,3,4,5,3,2])
print(np.argmin(var))

0


In [7]:
import numpy as np
var=np.array([1,2,3,4,5,3,2])
print(np.argmax(var))

4


In [11]:
var1=np.array([[2,1,3],[9,5,6]])  #axis=0 for column
print(np.min(var1,axis=1))
print(np.min(var1,axis=0))

[1 5]
[2 1 3]


In [17]:
var2=np.array([1,2,3])
print(np.sin(var2))
print(np.cos(var2))


[0.84147098 0.90929743 0.14112001]
[ 0.54030231 -0.41614684 -0.9899925 ]


In [19]:
print(np.cumsum(var2))

[1 3 6]


In [39]:
#reshape
var3=np.array([1,2,3,4,5,7,5,8,9,63,4,3])
print(var3)
x=var3.reshape(3,2,2) #reshape into 2
print(x) 
print(x.ndim)
x1=var3.reshape(-1) #reshape into original
print(x1) 
print(x1.ndim)

[ 1  2  3  4  5  7  5  8  9 63  4  3]
[[[ 1  2]
  [ 3  4]]

 [[ 5  7]
  [ 5  8]]

 [[ 9 63]
  [ 4  3]]]
3
[ 1  2  3  4  5  7  5  8  9 63  4  3]
1
