In [6]:
import numpy as np

var1=np.array([1,2,3,4,5,3,2])
print(var1.shape)
var2=np.array([1,2,3,4,5,3,2])
print(var1+var2)

(7,)
[ 2  4  6  8 10  6  4]


In [ ]:
#broadcasting
'''must same dimension
value commom or must have any one of them 1'''


In [14]:
var3=np.array([1,2,3])
print(var3.shape)
print()
print(var3)
var4=np.array([[1],[2],[3]])
print(var4.shape)
print()
print(var4)

print(var3+var4)

(3,)

[1 2 3]
(3, 1)

[[1]
 [2]
 [3]]
[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [22]:
x=np.array([[1],[2]])
print(x.shape)
y=np.array([[1,2,3],[1,2,3]])
print(y.shape)
print(x+y)

(2, 1)
(2, 3)
[[2 3 4]
 [3 4 5]]


In [30]:
#copy
var=np.array([1,2,3,4,5,3,2])
co=var.copy()
var[1]=40#create new array
print(var)
print(co)

[ 1 40  3  4  5  3  2]
[1 2 3 4 5 3 2]


In [34]:
var3=np.array([1,2,3,4,5,3,2])
vi=var3.view() 
vi[1]=40 #view of original
print(var3)
print(vi)

[ 1 40  3  4  5  3  2]
[ 1 40  3  4  5  3  2]
