In [3]:
import numpy as np
#empty 
ar_em=np.empty(4)
print(ar_em)

[2.12199579e-314 6.95293141e-310 6.60071703e-321 6.95293141e-310]


In [5]:
ar_rn=np.arange(4)
print(ar_rn)

[0 1 2 3]


In [7]:
#diagonal
ar_dia=np.eye(3)
ar_dia

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
#diagonal
ar_dia=np.eye(3,5)
ar_dia

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [13]:
#linspace
ar_lin=np.linspace(1,20,num=5)
ar_lin

array([ 1.  ,  5.75, 10.5 , 15.25, 20.  ])


Random


In [17]:
#with random numbers
#rand() 0--1
var=np.random.rand(4)
var

array([0.75674039, 0.91620332, 0.41667251, 0.53773573])

In [25]:
var1=np.random.rand(2,5) #2 * 5
print(var1)

[[0.6339627  0.49314868 0.9845571  0.44504847 0.56713888]
 [0.7219261  0.53684629 0.9913593  0.78739855 0.83717472]]


In [27]:
#randn() --> close to zero (+ve and -ve)
var2=np.random.rand(5)
var2


array([0.35214214, 0.01204121, 0.19781138, 0.53420278, 0.02399252])

In [29]:
#ranf() --> [0 to 1) but 1 not included
var3=np.random.ranf(5)
var3


array([0.48282709, 0.60261657, 0.61921456, 0.92012019, 0.29307018])

In [31]:
#randint() in a given range (min ,max,total_value)
var4=np.random.randint(5,20,5)
var4


array([12, 10, 15,  9, 14])