In [10]:
import numpy as np
arr1d=np.array([9,8,4,3])
print(arr1d[1])
print(arr1d[-3])


8
8


In [12]:

# Slice with positive indices
print(arr1d[2:5]) 

# Slice with negative indices
print(arr1d[-5:-2]) 

# Slicing with step
print(arr1d[1:8:2]) 

# Reverse the array
print(arr1d[::-1])  


[4 3]
[9 8]
[8 3]
[3 4 8 9]


In [6]:
# Creating a 2D array
arr2d = np.array([[0, 1, 2],
                  [3, 4, 5],
                  [6, 7, 8]])
# Access a single element
print(arr2d[1, 2]) 


5


In [14]:
# Slice rows
print(arr2d[1]) 

# Slice a specific part
print(arr2d[0:2, 1:3])  
                       

# Access entire rows or columns
print(arr2d[:, 1]) 
print(arr2d[1, :]) 


[3 4 5]
[[1 2]
 [4 5]]
[1 4 7]
[3 4 5]


In [16]:
# Creating a 3D array
arr3d = np.array([[[0, 1, 2],
                   [3, 4, 5]],
                  
                  [[6, 7, 8],
                   [9, 10, 11]]])
# Access a single element
print(arr3d[1, 0, 2])  #(second block, first row, third column)


8


In [22]:
# Slice along one axis
print(arr3d[0])  #  (first 2D block)
print()
# Slice specific rows and columns
print(arr3d[:, 1, :]) # (all blocks, second row)
print()
# Slice specific parts across dimensions
print(arr3d[:, :, 1:3])  #  [[[ 1  2]
                         #           [ 4  5]]
                         #
                         #          [[ 7  8]
                         #           [10 11]]]


[[0 1 2]
 [3 4 5]]

[[ 3  4  5]
 [ 9 10 11]]

[[[ 1  2]
  [ 4  5]]

 [[ 7  8]
  [10 11]]]


In [ ]:
'''arr2d[:, 1]: Extracts the second column across all rows.
arr2d[1, :]: Extracts the second row across all columns.'''

'''arr3d[:, :, 1:3]:
Selects all blocks, all rows, and the second and third columns.'''