In [7]:
import numpy as np

# Define a NumPy array
array = np.array([[1, 2,3], [1,2,3]])

# Define a NumPy matrix
matrix = np.matrix([[1, 2,3], [1,2,3]])
print(array)
print()
print(matrix)
print()
# Check types
print("Type of 'array':", type(array))   
print("Type of 'matrix':", type(matrix))


[[1 2 3]
 [1 2 3]]

[[1 2 3]
 [1 2 3]]

Type of 'array': <class 'numpy.ndarray'>
Type of 'matrix': <class 'numpy.matrix'>


In [11]:
#Arithmetic 
import numpy as np

array = np.array([[1, 2], [3, 4]])


matrix = np.matrix([[1, 2], [3, 4]])

print( array)
print( matrix)

# Addition
array_addition = array + array
matrix_addition = matrix + matrix
print("\nAddition:")
print("Array:\n", array_addition)
print("Matrix:\n", matrix_addition)

# Subtraction
array_subtraction = array - array
matrix_subtraction = matrix - matrix
print("\nSubtraction:")
print("Array:\n", array_subtraction)
print("Matrix:\n", matrix_subtraction)

# Element-wise Multiplication
array_multiplication = array * array  # Element-wise for arrays
matrix_multiplication = np.multiply(matrix, matrix)  # Element-wise for matrices
print("\nElement-wise Multiplication:")
print("Array:\n", array_multiplication)
print("Matrix:\n", matrix_multiplication)

# Matrix Multiplication
array_dot_product = array @ array  # or np.matmul(array, array)
matrix_dot_product = matrix * matrix  # Matrix multiplication for matrices
print("\nMatrix Multiplication:")
print("Array (dot product):\n", array_dot_product)
print("Matrix (dot product):\n", matrix_dot_product)

# Division
array_division = array / 2
matrix_division = matrix / 2
print("\nDivision by 2:")
print("Array:\n", array_division)
print("Matrix:\n", matrix_division)


[[1 2]
 [3 4]]
[[1 2]
 [3 4]]

Addition:
Array:
 [[2 4]
 [6 8]]
Matrix:
 [[2 4]
 [6 8]]

Subtraction:
Array:
 [[0 0]
 [0 0]]
Matrix:
 [[0 0]
 [0 0]]

Element-wise Multiplication:
Array:
 [[ 1  4]
 [ 9 16]]
Matrix:
 [[ 1  4]
 [ 9 16]]

Matrix Multiplication:
Array (dot product):
 [[ 7 10]
 [15 22]]
Matrix (dot product):
 [[ 7 10]
 [15 22]]

Division by 2:
Array:
 [[0.5 1. ]
 [1.5 2. ]]
Matrix:
 [[0.5 1. ]
 [1.5 2. ]]


In [19]:
# Transpose of a Matrix


# Define a matrix
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Transpose
transpose_matrix = matrix.T



print("Original Matrix:\n", matrix)
print("Transpose of the Matrix:\n", transpose_matrix)
print()
print(np.transpose(matrix))

Original Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Transpose of the Matrix:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [21]:
#. Swap Axes of a Matrix

swapped_matrix = np.swapaxes(matrix, 0, 1)

print("Matrix after Swapping Axes:\n", swapped_matrix)


Matrix after Swapping Axes:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


In [23]:
#3. Inverse of a Matrix
# Define a square matrix
square_matrix = np.array([[4, 7], [2, 6]])

# Inverse
try:
    inverse_matrix = np.linalg.inv(square_matrix)
    print("Original Matrix:\n", square_matrix)
    print("Inverse of the Matrix:\n", inverse_matrix)
except np.linalg.LinAlgError:
    print("Matrix is singular and cannot be inverted.")


Original Matrix:
 [[4 7]
 [2 6]]
Inverse of the Matrix:
 [[ 0.6 -0.7]
 [-0.2  0.4]]


In [37]:
#. Matrix Power



# Define a square matrix
square_matrix = np.array([[4, 7], [2, 6]])

# Compute the power of the matrix
# Power of 2
matrix_power_2 = np.linalg.matrix_power(square_matrix, 2)
print("Matrix raised to power 2:\n", matrix_power_2)

# Power of 0 (Identity Matrix)
matrix_power_0 = np.linalg.matrix_power(square_matrix, 0)
print("\nMatrix raised to power 0 (Identity Matrix):\n", matrix_power_0)

# Power of -2 (Inverse Squared)
try:
    matrix_power_neg2 = np.linalg.matrix_power(square_matrix, -2)
    print("\nMatrix raised to power -2 (Inverse Squared):\n", matrix_power_neg2)
except np.linalg.LinAlgError:
    print("\nMatrix is singular and cannot be inverted for negative powers.")

# Display the original matrix for reference
print("\nOriginal Matrix:\n", square_matrix)


Matrix raised to power 2:
 [[30 70]
 [20 50]]

Matrix raised to power 0 (Identity Matrix):
 [[1 0]
 [0 1]]

Matrix raised to power -2 (Inverse Squared):
 [[ 0.5 -0.7]
 [-0.2  0.3]]

Original Matrix:
 [[4 7]
 [2 6]]


In [35]:
#Determinant of a Matrix

determinant = np.linalg.det(square_matrix)

print("Matrix:\n", square_matrix)
print("Determinant of the Matrix:\n", determinant)


Matrix:
 [[4 7]
 [2 6]]
Determinant of the Matrix:
 10.000000000000002
