In [1]:
import numpy as np
var=np.array([1,2,3,4])
print(var)

[1 2 3 4]


In [3]:
np.insert(var,2,40)
#also with np.append(var,2,40)

array([ 1,  2, 40,  3,  4])

In [7]:
np.insert(var,(2,4),6.5) #float value cant accpet only in int

array([1, 2, 6, 3, 4, 6])

In [11]:
var1=np.array([[1,2,3,4],[1,2,3,4]])
v1=np.insert(var1,2,6,axis=0)
v1

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [6, 6, 6, 6]])

In [21]:
var1=np.array([[1,2,3],[1,2,3]])
#also with np.append(var1,2,[22,33,24],axis=0)
v1=np.insert(var1,2,6,axis=1)
v1

array([[1, 2, 6, 3],
       [1, 2, 6, 3]])

In [25]:
var1=np.array([[1,2,3],[1,2,3]])
v1=np.insert(var1,2,[6,7,8],axis=0)
v1

array([[1, 2, 3],
       [1, 2, 3],
       [6, 7, 8]])

In [27]:
import numpy as np
var2=np.array([1,2,3,4])
print(var2)
d=np.delete(var2,2)
print(d)

[1 2 3 4]
[1 2 4]
