In [4]:
import numpy as np

# 1D Array
array_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:", array_1d)

#2nd
X=[1,2,3,4]
Y=np.array([X])
print(Y)
print(type[Y])

#by user input
L=[]
for i in range(1,6):
     Int_1=input("enter: ")
     L.append(Int_1)
print(np.array(L))


# 2D Array
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", array_2d)

# 3D Array
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("3D Array:\n", array_3d)

# Higher Dimensional Array
array_high_dim = np.array([1, 2, 3, 4], ndmin=4)
print("Higher Dimensional Array:\n", array_high_dim)

# Array Creation Using NumPy Functions
# 3x3 matrix of zeros
zeros_array = np.zeros((3, 3))
print("Zeros Array:\n", zeros_array)

ones_array = np.ones((2, 2))  # 2x2 matrix of ones
print("Ones Array:\n", ones_array)

range_array = np.arange(0, 10, 2)  # Array from 0 to 10 with step 2
print("Range Array:", range_array)

linspace_array = np.linspace(0, 1, 5)  # 5 equally spaced numbers between 0 and 1
print("Linspace Array:", linspace_array)

# Reshaping Arrays
reshaped_array = np.arange(12).reshape(3, 4)  # Reshaping into 3x4 matrix
print("Reshaped Array:\n", reshaped_array)

1D Array: [1 2 3 4 5]
[[1 2 3 4]]
type[array([[1, 2, 3, 4]])]
enter: 14
enter: 45
enter: 67
enter: 23
enter: 
['14' '45' '67' '23' '']
2D Array:
 [[1 2 3]
 [4 5 6]]
3D Array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Higher Dimensional Array:
 [[[[1 2 3 4]]]]
Zeros Array:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Ones Array:
 [[1. 1.]
 [1. 1.]]
Range Array: [0 2 4 6 8]
Linspace Array: [0.   0.25 0.5  0.75 1.  ]
Reshaped Array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
